[package]
name = "spn-prover"
description = "Prover for SPN."
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
spn-artifacts = { workspace = true }
spn-network-types = { workspace = true }
spn-logging = { workspace = true }
spn-utils = { workspace = true }
spn-fee = { workspace = true }
sp1-sdk = { version = "4.1.0", features = ["native-gnark"] }
sp1-prover = { version = "4.1.0" }

anyhow = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }
alloy = { workspace = true }
alloy-signer-local = { workspace = true }
hex = { workspace = true }
config = { workspace = true }
futures = { workspace = true }
const-str = { workspace = true }
bincode = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true }
